autocreate-playlist=same
autofit-larger=100%x100%
clipboard-backends=vo
deband=yes
geometry=50%:50%
hwdec=auto
keep-open=yes
osd-font="Adwaita Sans"
resume-playback=yes
save-position-on-quit=yes
save-watch-history=yes
screenshot-directory=~/Pictures/mpv
sub-auto=all
sub-file-paths=ass:Ass:srt:Srt:sub:Sub:subtitles:Subtitles:subs:Subs
sub-scale-with-window=no
sub-scale=1.5
vo=gpu-next
volume-max=150
volume=125
window-maximized=yes
write-filename-in-watch-later-config=yes

# Disable history for ~/Music folder
[no-music-history]
profile-cond=get("path", ""):match("^" .. os.getenv("HOME") .. "/Music/") ~= nil
profile-restore=copy
save-watch-history=no

# OSC visible on pause
[pause]
profile-cond=pause
profile-restore=copy
script-opt=osc-visibility=always
