autofit-larger=100%x100%
border=no
geometry=50%:50%
hwdec=auto
keep-open=yes
osc=no
osd-bar=no
osd-font="Adwaita Sans"
resume-playback=yes
save-position-on-quit=yes
save-watch-history=yes
sub-auto=all
sub-scale-with-window=no
sub-scale=1.5
window-maximized=yes
write-filename-in-watch-later-config=yes

# Disable history for ~/Music folder
[no-music-history]
profile-cond=get("path", ""):match("^" .. os.getenv("HOME") .. "/Music/") ~= nil
profile-restore=copy
save-watch-history=no
