" Background style
set background=dark
" set background=light

" Dark theme
if (&background == 'dark')
    colorscheme vim-material
" Light theme
elseif (&background == 'light')
    colorscheme vim-material
endif

" Set font
set gfn=JetBrains\ Mono\ NL\ 11
set linespace=-1

" Be quiet
set vb t_vb=""

" Remove toolbar
set guioptions-=T

" Remove scroolbar
set guioptions-=L
set guioptions-=l
set guioptions-=R
set guioptions-=r
set guioptions-=b

" Remove menu
set guioptions-=m

" Disable Cursor blink
set guicursor+=a:blinkon0
