Config.later(function()
  vim.pack.add({ "https://github.com/nvim-mini/mini.nvim" })
  require("mini.bufremove").setup()
  vim.api.nvim_create_user_command("BD", function() MiniBufremove.delete(0, true) end, {})
  vim.api.nvim_create_user_command("BW", function() MiniBufremove.wipeout(0, true) end, {})
end)
